test: test-testQuestao5
	./build/testQuestao5

test-testQuestao5: test/testQuestao5.cpp
	g++ -Wall -Wextra -Werror -g test/testQuestao5.cpp -o build/testQuestao5

debug-questao5:
	gdb build/testQuestao5

clean: 
	rm -rf build/*

run: