test: test-testQuestao6
	./build/testQuestao6

test-testQuestao6: test/testQuestao6.cpp
	g++ -Wall -Wextra -Werror -g test/testQuestao6.cpp -o build/testQuestao6

debug-questao5:
	gdb build/testQuestao6

clean: 
	rm -rf build/*

run: