test: test-testQuestao4
	./build/testQuestao4

test-testQuestao4: test/testQuestao4.cpp
	g++ -Wall -Wextra -Werror -g test/testQuestao4.cpp -o build/testQuestao4

debug-questao4:
	gdb build/testQuestao4

clean: 
	rm -rf build/*

run: