name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: questao1
      run: make -C questao_1 test
    - name: questao2
      run: make -C questao_2 test
    - name: questao3
      run: make -C questao_3 test
